#pragma config(Motor,  port2,           left,          tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           right,         tmotorVex393, openLoop)
#pragma config(Motor,  port4,           lefta,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           rightb,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           righta,        tmotorVex393, openLoop)
#pragma config(Motor,  port9,           leftb,         tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
}

task autonomous() {
}
task usercontrol()
{
	// User control code here, inside the loop

	while(true)
	{
		int Ch3a= abs(vexRT[Ch3]) < 8 ? 0 : vexRT[Ch3];
		int Ch4a= abs(vexRT[Ch4]) < 8 ? 0 : vexRT[Ch4];
	  motor[right] = motor[port8] = motor[rightb] = Ch3a - Ch4a;
	 	motor[left] = motor[port4] = motor[leftb] = Ch3a + Ch4a;
	}
}
